//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class asesoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asesoria()
        {
            this.evaluacions = new HashSet<evaluacion>();
            this.reportes = new HashSet<reporte>();
            this.solicituds = new HashSet<solicitud>();
        }
    
        public int IdAsesoria { get; set; }
        public int IdAsesor { get; set; }
        public int IdUnidadAprendizaje { get; set; }
        public string CicloEscolar { get; set; }
        public int IdLugar { get; set; }
        public int IdHorario { get; set; }
    
        public virtual asesor asesor { get; set; }
        public virtual cat_horario cat_horario { get; set; }
        public virtual cat_lugar cat_lugar { get; set; }
        public virtual cat_unidad_aprendizaje cat_unidad_aprendizaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evaluacion> evaluacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporte> reportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud> solicituds { get; set; }
    }
}
