//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int IdAsistencia { get; set; }
        public int IdReporte { get; set; }
        public int IdAlumno { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual reporte reporte { get; set; }
    }
}
