//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int IdAsistencia { get; set; }
        public int IdReporte { get; set; }
        public int IdAlumno { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual reporte reporte { get; set; }
    }
}
