//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluacion
    {
        public int IdEvaluacion { get; set; }
        public int IdAlumno { get; set; }
        public int IdAsesoria { get; set; }
        public string MedioConocimiento { get; set; }
        public string DesempenoAlumno { get; set; }
        public string DesempenoAsesor { get; set; }
        public string PuntualidadAsesor { get; set; }
        public string ActitudAsesor { get; set; }
        public string LenguajeAsesor { get; set; }
        public string EspacioAdecuado { get; set; }
        public string CambioEspacio { get; set; }
        public string Mejora { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual asesoria asesoria { get; set; }
    }
}
