//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluacion
    {
        public int IdEvaluacion { get; set; }
        public int IdAlumno { get; set; }
        public int IdAsesoria { get; set; }
        public string MedioConocimiento { get; set; }
        public string DesempenoAlumno { get; set; }
        public string DesempenoAsesor { get; set; }
        public string PuntualidadAsesor { get; set; }
        public string ActitudAsesor { get; set; }
        public string LenguajeAsesor { get; set; }
        public string EspacioAdecuado { get; set; }
        public string CambioEspacio { get; set; }
        public string Mejora { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual asesoria asesoria { get; set; }
    }
}
