//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reporte()
        {
            this.asistencias = new HashSet<asistencia>();
        }
    
        public int IdReporte { get; set; }
        public int IdAsesoria { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Duracion { get; set; }
        public int IdTemaVisto { get; set; }
        public string Comentarios { get; set; }
    
        public virtual asesoria asesoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencia> asistencias { get; set; }
        public virtual cat_temas cat_temas { get; set; }
    }
}
