//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public int Idsolicitud { get; set; }
        public int IdAlumno { get; set; }
        public int IdAsesoria { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAceptacion { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual cat_estado cat_estado { get; set; }
        public virtual asesoria asesoria { get; set; }
    }
}
