//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Contrasena { get; set; }
        public Nullable<int> IdProgramaEducativo { get; set; }
        public int IdTipoUsuario { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual asesor asesor { get; set; }
        public virtual cat_estatus cat_estatus { get; set; }
        public virtual cat_programa_educativo cat_programa_educativo { get; set; }
        public virtual cat_tipo_usuario cat_tipo_usuario { get; set; }
        public virtual encargado encargado { get; set; }
    }
}
